name: Docker runner image

on:
  push:
    branches:
      - master
    paths:
      - 'docker-images/runner/Dockerfile'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-20.04
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x ]
        is-ci: [ 'true' ]
        include:
          - node-version: 16.x
            is-ci: 'false'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          if [ "${{ matrix.is-ci }}" = "true" ]; then
            IMAGE_TAG="ci-${{ matrix.python-version }}"
          else
            IMAGE_TAG="cd-${{ matrix.python-version }}"
          fi

          docker build --build-arg PYTHON_VERSION="${{ matrix.python-version }}" \
          --build-arg IS_CI="${{ matrix.is-ci }}" \
          --no-cache \
          --progress=plain \
          --tag $DOCKER_USERNAME/PROJECTNAME-runner:$IMAGE_TAG \
          --file docker-images/runner/Dockerfile .

      - name: Push image to Docker Hub
        run: |
          if [ "${{ matrix.is-ci }}" = "true" ]; then
            IMAGE_TAG="ci-${{ matrix.python-version }}"
          else
            IMAGE_TAG="cd-${{ matrix.python-version }}"
          fi

          docker push $DOCKER_USERNAME/PROJECTNAME-runner:$IMAGE_TAG

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)
